name: Manual Tests

on:
  workflow_dispatch:
    inputs:
      test_option:
        description: 'Choose test set'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
          - 'test_stock_symbols'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List Python versions
      run: |
        python --version
        python3 --version
        if command -v python3.9 &> /dev/null; then
          python3.9 --version
        else
          echo "Python 3.9 not installed"
        fi

    - name: Run tests based on input
      run: |
        if [ "${{ github.event.inputs.test_option }}" = "test_stock_symbols" ]; then
          python -m pytest -v -k "test_stock_symbols"
        else
          python -m pytest -v
        fi


