name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test_option:
        description: 'Choose test set'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
          - 'test_stock_symbols'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]  # Running only on Python 3.11

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Chromedriver
      run: |
        sudo apt-get install -yqq unzip
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests based on input
      run: |
        if [ "${{ github.event.inputs.test_option }}" == "test_stock_symbols" ]; then
          pytest -v -k "test_stock_symbols"
        else
          pytest -v
        fi


