name: Manual Run

on:
  workflow_dispatch:
    inputs:
      test_option:
        description: 'Choose test set'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
          - 'test_stock_symbols'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Only use Python 3.11

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Chromedriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests based on input
      run: |
        if [ "${{ github.event.inputs.test_option }}" = "test_stock_symbols" ]; then
          pytest -v -k "test_stock_symbols"
        else:
          pytest -v

    - name: Verify Chrome and Chromedriver versions
      run: |
        google-chrome --version
        chromedriver --version

